package io.github.krindor.ffxivsimulator.skills;

public enum AstrologianSkill {
    Draw,
    Royal_Road,
    Spread,
    Redraw,
    Benefic,
    Aspected_Benefic,
    Malefic,
    Stella,
    Malefic_II,
    Combust,
    Helios,
    Aspected_Helios,
    Exalted_Detriment,
    Ascend,
    Diurnal_Sect,
    Nocturnal_Sect,
    Lightspeed,
    Luminiferous_Aether,
    Combust_II,
    Disable,
    Benefic_II,
    Time_Dilation,
    Synastry,
    Collective_Unconscious,
    Essential_Dignity,
    Gravity,
    Celestial_Opposition,
    The_Balance,
    The_Bole,
    The_Arrow,
    The_Spear,
    The_Ewer,
    The_Spire
}