package io.github.krindor.ffxivsimulator.skills;

public enum MachinistSkill {
    Rook_Autoturret,
    Bishop_Autoturret,
    Split_Shot,
    Reload,
    Slug_Shot,
    Lead_Shot,
    Spread_Shot,
    Grenado_Shot,
    Hot_Shot,
    Clean_Shot,
    Gauss_Round,
    Heartbreak,
    Reassemble,
    Leg_Graze,
    Wildfire,
    Quick_Reload,
    Gauss_Barrel,
    Rapid_Fire,
    Rend_Mind,
    Suppressive_Fire,
    Foot_Graze,
    Hypercharge,
    Head_Graze,
    Dismantle,
    Blank,
    Promotion,
    Ricochet,
    Turret_Retrieval
}